"""Add LlmModel and ModelUsageStat tables

Revision ID: 15411dafef04
Revises: 507845a770ab
Create Date: 2026-03-21 19:43:16.989767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15411dafef04'
down_revision: Union[str, None] = '507845a770ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_models',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('support_thinking', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_usage_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'user_id', 'model_id', name='uq_usage_stat_dim')
    )
    op.create_index('idx_usage_stat', 'model_usage_stats', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_usage_stat', table_name='model_usage_stats')
    op.drop_table('model_usage_stats')
    op.drop_table('llm_models')
    # ### end Alembic commands ###
