"""add is_deleted to question

Revision ID: 1aa8cb7052f7
Revises: fcce239ce78a
Create Date: 2026-03-21 16:19:28.702434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa8cb7052f7'
down_revision: Union[str, None] = 'fcce239ce78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'is_deleted')
    # ### end Alembic commands ###
