"""add index to session_id

Revision ID: fcce239ce78a
Revises: d6dee348365f
Create Date: 2026-03-21 15:21:04.649101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcce239ce78a'
down_revision: Union[str, None] = 'd6dee348365f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_session_id', 'questions', ['session_id'], unique=False)
    op.create_index(op.f('ix_questions_session_id'), 'questions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_session_id'), table_name='questions')
    op.drop_index('idx_session_id', table_name='questions')
    # ### end Alembic commands ###
